// Direct imports instead of lazy loading to eliminate chunk.js files
import AdminDashboard from '@/pages/AdminDashboard';
import EmailMarketing from '@/pages/EmailMarketing';
import BacklinkReport from '@/pages/BacklinkReport';
import ReportViewer from '@/pages/ReportViewer';
import SavedReports from '@/pages/SavedReports';
import NoHandsSEO from '@/pages/NoHandsSEO';
import PromotionMaterials from '@/pages/PromotionMaterials';
import Affiliate from '@/pages/Affiliate';
import { CampaignDeliverables } from '@/pages/CampaignDeliverables';
import { BlogCreator } from '@/pages/BlogCreator';
import { BlogPost } from '@/pages/BlogPost';
import Blog from '@/pages/Blog';
import { BlogListing } from '@/pages/BlogListing';
import { BlogCreation } from '@/pages/BlogCreation';
import { EnhancedBlogListing } from '@/components/EnhancedBlogListing';
import { SuperEnhancedBlogListing } from '@/components/SuperEnhancedBlogListing';
import { BeautifulBlogPost } from '@/components/BeautifulBlogPost';
import { BeautifulBlogTemplate } from '@/components/BeautifulBlogTemplate';
import BlogValidator from '@/pages/BlogValidator';
import { TrialDashboard } from '@/pages/TrialDashboard';
import AIContentTest from '@/pages/AIContentTest';
import { ClaimSystemDebug } from '@/components/ClaimSystemDebug';
import { EnhancedDashboardRouter } from '@/components/EnhancedDashboardRouter';
import { UserBlogManagement } from '@/components/UserBlogManagement';
import { BlogEditPage } from '@/pages/BlogEditPage';
import { EnhancedAILive } from '@/components/EnhancedAILive';
import { GuestDashboard } from '@/components/GuestDashboard';
import SEOBlogGenerator from '@/pages/SEOBlogGenerator';
import ScrapePage from '@/pages/ScrapePage';
import Automation from '@/pages/Automation';
import DomainsManager from '@/pages/DomainsManager';
import AdminCampaignManager from '@/pages/AdminCampaignManager';
import OpenAITest from '@/pages/OpenAITest';
import { SystemTest } from '@/components/SystemTest';
import PaymentDiagnostic from '@/pages/PaymentDiagnostic';
import EdgeFunctionDiagnostic from '@/pages/EdgeFunctionDiagnostic';
import RouteSyncTest from '@/pages/RouteSyncTest';
import EmailAuthenticationAudit from '@/pages/EmailAuthenticationAudit';
import EmailDiagnostic from '@/pages/EmailDiagnostic';

// Export as "Lazy" names for backward compatibility (they're just direct imports now)
export const LazyAdminDashboard = AdminDashboard;
export const LazyEmailMarketing = EmailMarketing;
export const LazyBacklinkReport = BacklinkReport;
export const LazyReportViewer = ReportViewer;
export const LazySavedReports = SavedReports;
export const LazyNoHandsSEO = NoHandsSEO;
export const LazyPromotionMaterials = PromotionMaterials;
export const LazyAffiliateProgram = Affiliate;
export const LazyCampaignDeliverables = CampaignDeliverables;
export const LazyBlogCreator = BlogCreator;
export const LazyBlogPost = BlogPost;
export const LazyBlog = Blog;
export const LazyBlogListing = BlogListing;
export const LazyBlogCreation = BlogCreation;
export const LazyBlogPostView = BlogPost;
export const LazyEnhancedBlogListing = EnhancedBlogListing;
export const LazySuperEnhancedBlogListing = SuperEnhancedBlogListing;
export const LazyBeautifulBlogPost = BeautifulBlogPost;
export const LazyBeautifulBlogTemplate = BeautifulBlogTemplate;
export const LazyBlogValidator = BlogValidator;
export const LazyTrialDashboard = TrialDashboard;
export const LazyAIContentTest = AIContentTest;
export const LazyClaimSystemDebug = ClaimSystemDebug;
export const LazyEnhancedDashboardRouter = EnhancedDashboardRouter;
export const LazyUserBlogManagement = UserBlogManagement;
export const LazyBlogEditPage = BlogEditPage;
export const LazyEnhancedAILive = EnhancedAILive;
export const LazyGuestDashboard = GuestDashboard;
export const LazySEOOptimizedBlogGenerator = SEOBlogGenerator;
export const LazyScrapePage = ScrapePage;
export const LazyAutomation = Automation;
export const LazyDomainsManager = DomainsManager;
export const LazyAdminCampaignManager = AdminCampaignManager;
export const LazyOpenAITest = OpenAITest;
export const LazySystemTest = SystemTest;
export const LazyPaymentDiagnostic = PaymentDiagnostic;
export const LazyEdgeFunctionDiagnostic = EdgeFunctionDiagnostic;
export const LazyRouteSyncTest = RouteSyncTest;
export const LazyEmailAuthenticationAudit = EmailAuthenticationAudit;
export const LazyEmailDiagnostic = EmailDiagnostic;
