#!/bin/bash

# Video replacement mapping for all pages
declare -A VIDEO_MAP=(
  ["ab-testing-anchor-texts"]="3PU3HBk7YYU"
  ["affordable-link-building-services"]="LIKqATBKl-A"
  ["ahrefs-for-link-building"]="3MnqGJb3PGE"
  ["ai-powered-link-building"]="j8hQrMtqNrk"
  ["anchor-text-optimization-for-backlinks"]="3PU3HBk7YYU"
  ["are-paid-backlinks-worth-it"]="5HKvkBIBf8o"
  ["authoritative-backlinks-for-e-commerce"]="j8hQrMtqNrk"
  ["backlink-building-for-beginners"]="Q7F01_OXNqo"
  ["backlink-disavow-tool-usage"]="VxW4KKvQlHs"
  ["backlink-dr-vs-ur-metrics"]="YdB6UfO0eHE"
  ["backlink-equity-calculation"]="WjQLLj0nBLY"
  ["backlink-farming-risks"]="2R-3X3kY9W8"
  ["backlink-growth-tracking"]="3MnqGJb3PGE"
  ["backlink-indexing-techniques"]="lVKvr5PEf-g"
  ["backlink-negotiation-scripts"]="BXp6pVW6zVc"
  ["backlink-profile-diversification"]="pq6_sTu_TJ0"
  ["backlink-quality-factors"]="M7lc1BCxL00"
  ["backlink-relevancy-best-practices"]="3PU3HBk7YYU"
  ["backlink-score-improvement"]="jGxFxv2D5d0"
  ["backlink-strategy-for-local-business"]="6McePZz4XZM"
  ["backlink-types-explained"]="nZl1PGr6K9o"
  ["best-backlink-marketplaces"]="M7lc1BCxL00"
  ["best-backlink-monitoring-tools"]="3MnqGJb3PGE"
  ["best-backlink-services-review"]="lVKvr5PEf-g"
  ["best-guest-posting-platforms"]="BXp6pVW6zVc"
  ["best-link-building-agencies"]="j8hQrMtqNrk"
  ["best-link-building-courses"]="Q7F01_OXNqo"
  ["best-seo-backlinking-tools"]="3MnqGJb3PGE"
  ["blogger-outreach-for-backlinks"]="BXp6pVW6zVc"
  ["broken-backlink-recovery"]="pq6_sTu_TJ0"
  ["broken-link-building-guide"]="pq6_sTu_TJ0"
  ["broken-link-building-method"]="pq6_sTu_TJ0"
  ["buying-backlinks-safely"]="M7lc1BCxL00"
  ["cheap-backlinks-vs-premium"]="5HKvkBIBf8o"
  ["competitive-seo-backlink-analysis"]="3MnqGJb3PGE"
  ["content-distribution-backlinks"]="sOzlmuHvZUI"
  ["content-syndication-for-backlinks"]="j8hQrMtqNrk"
  ["contextual-backlinks-guide"]="3PU3HBk7YYU"
  ["create-high-authority-backlinks"]="Q7F01_OXNqo"
  ["custom-backlink-strategy"]="jGxFxv2D5d0"
  ["da-pa-backlink-metrics"]="YdB6UfO0eHE"
  ["edu-backlink-strategies"]="M7lc1BCxL00"
  ["effective-backlink-outreach"]="BXp6pVW6zVc"
  ["ecommerce-backlink-seo-guide"]="j8hQrMtqNrk"
  ["enterprise-link-building-strategy"]="Q7F01_OXNqo"
  ["expert-roundup-backlinks"]="BXp6pVW6zVc"
  ["forum-backlinks-strategy"]="nZl1PGr6K9o"
  ["free-backlinks-methods"]="sOzlmuHvZUI"
  ["guest-post-backlink-strategy"]="BXp6pVW6zVc"
  ["guest-post-email-templates"]="BXp6pVW6zVc"
  ["high-authority-blog-backlinks"]="Q7F01_OXNqo"
  ["high-quality-link-building-services"]="j8hQrMtqNrk"
  ["how-many-backlinks-needed"]="M7lc1BCxL00"
  ["how-to-analyze-backlink-quality"]="3MnqGJb3PGE"
  ["how-to-build-backlinks-fast"]="lVKvr5PEf-g"
  ["how-to-check-backlinks"]="3MnqGJb3PGE"
  ["how-to-do-backlink-outreach"]="BXp6pVW6zVc"
  ["how-to-find-backlink-opportunities"]="3MnqGJb3PGE"
  ["how-to-get-organic-backlinks"]="sOzlmuHvZUI"
  ["industry-specific-backlink-tips"]="j8hQrMtqNrk"
  ["influencer-link-building"]="BXp6pVW6zVc"
  ["influencer-outreach-for-backlinks"]="BXp6pVW6zVc"
  ["infographic-backlink-method"]="sOzlmuHvZUI"
  ["internal-links-vs-backlinks"]="M7lc1BCxL00"
  ["keyword-research-for-link-building"]="j8hQrMtqNrk"
  ["link-audit-and-cleanup"]="3MnqGJb3PGE"
  ["link-bait-content-ideas"]="sOzlmuHvZUI"
  ["link-building-automation-tools"]="jGxFxv2D5d0"
  ["link-building-for-affiliate-sites"]="j8hQrMtqNrk"
  ["link-building-for-saas-companies"]="j8hQrMtqNrk"
  ["link-building-kpis"]="jGxFxv2D5d0"
  ["link-building-scams-to-avoid"]="M7lc1BCxL00"
  ["link-buying-vs-organic"]="5HKvkBIBf8o"
  ["link-exchange-risks"]="2R-3X3kY9W8"
  ["link-indexing-services"]="lVKvr5PEf-g"
  ["link-insertion-backlinks"]="3PU3HBk7YYU"
  ["link-magnet-content-types"]="sOzlmuHvZUI"
  ["local-backlink-strategies"]="6McePZz4XZM"
  ["manual-backlink-outreach"]="BXp6pVW6zVc"
  ["manual-vs-automated-link-building"]="jGxFxv2D5d0"
  ["micro-niche-backlinks"]="j8hQrMtqNrk"
  ["natural-backlink-growth"]="sOzlmuHvZUI"
  ["niche-edits-guide"]="3PU3HBk7YYU"
  ["nicheoutreach-backlinks"]="BXp6pVW6zVc"
  ["outreach-personalization-tips"]="BXp6pVW6zVc"
  ["parasite-seo-backlink-strategy"]="M7lc1BCxL00"
  ["pdf-backlinks-technique"]="sOzlmuHvZUI"
  ["press-release-backlinks"]="lVKvr5PEf-g"
  ["private-blog-network-risks"]="2R-3X3kY9W8"
  ["profile-backlinks-guide"]="3PU3HBk7YYU"
  ["quick-backlink-wins"]="lVKvr5PEf-g"
  ["resource-page-link-building"]="BXp6pVW6zVc"
  ["review-backlink-services"]="j8hQrMtqNrk"
  ["seo-link-pyramids"]="jGxFxv2D5d0"
  ["seo-ranking-with-backlinks"]="M7lc1BCxL00"
  ["skyscraper-backlink-technique"]="pq6_sTu_TJ0"
  ["social-media-signal-backlinks"]="sOzlmuHvZUI"
  ["spam-score-reduction-for-links"]="3MnqGJb3PGE"
  ["spyfu-competitor-backlinks"]="3MnqGJb3PGE"
  ["tech-startup-backlinks"]="j8hQrMtqNrk"
  ["top-backlink-providers-reviewed"]="j8hQrMtqNrk"
  ["topical-authority-through-links"]="Q7F01_OXNqo"
  ["toxic-backlink-removal"]="3MnqGJb3PGE"
  ["travel-blog-guest-posts"]="BXp6pVW6zVc"
  ["ultimate-link-building-checklist"]="Q7F01_OXNqo"
  ["video-seo-backlinks"]="sOzlmuHvZUI"
  ["voice-search-backlink-optimization"]="j8hQrMtqNrk"
  ["web3-link-building-nfts"]="M7lc1BCxL00"
  ["where-to-find-high-quality-backlinks"]="3MnqGJb3PGE"
  ["white-hat-link-building-techniques"]="lVKvr5PEf-g"
  ["xrumer-backlink-automation"]="2R-3X3kY9W8"
  ["zero-click-search-link-strategies"]="M7lc1BCxL00"
  ["gsa-search-engine-ranker-alternatives"]="jGxFxv2D5d0"
  ["buy-backlinks-from-authority-sites"]="5HKvkBIBf8o"
  ["buy-contextual-backlinks"]="3PU3HBk7YYU"
  ["buy-high-quality-backlinks"]="Q7F01_OXNqo"
  ["buy-niche-relevant-backlinks"]="j8hQrMtqNrk"
  ["buy-pbn-backlinks-safely"]="2R-3X3kY9W8"
  ["buzzsumo-for-link-opportunities"]="3MnqGJb3PGE"
  ["case-study-high-quality-backlinks"]="Q7F01_OXNqo"
  ["conversion-optimized-backlinks"]="j8hQrMtqNrk"
  ["core-web-vitals-and-backlinks"]="M7lc1BCxL00"
  ["directory-submission-link-building"]="6McePZz4XZM"
  ["diy-link-building-tools"]="3MnqGJb3PGE"
  ["do-backlinks-still-work-in-2025"]="M7lc1BCxL00"
  ["e-commerce-backlink-packages"]="j8hQrMtqNrk"
  ["e-e-a-t-signals-via-backlinks"]="M7lc1BCxL00"
  ["ethical-black-hat-alternatives"]="lVKvr5PEf-g"
  ["fashion-industry-link-building"]="j8hQrMtqNrk"
  ["finance-site-link-acquisition"]="jGxFxv2D5d0"
  ["fiverr-vs-upwork-for-links"]="BXp6pVW6zVc"
  ["forum-link-building-tips"]="nZl1PGr6K9o"
  ["free-backlink-opportunities-2025"]="sOzlmuHvZUI"
  ["gaming-niche-backlink-strategies"]="j8hQrMtqNrk"
  ["google-penguin-recovery-backlinks"]="2R-3X3kY9W8"
  ["haro-link-building-guide"]="BXp6pVW6zVc"
  ["health-blog-link-building"]="jGxFxv2D5d0"
  ["high-da-backlinks-for-sale"]="Q7F01_OXNqo"
  ["high-quality-backlinks-from-.edu-sites"]="M7lc1BCxL00"
  ["high-quality-backlinks-vs-low-quality"]="3MnqGJb3PGE"
  ["how-much-do-backlinks-cost"]="5HKvkBIBf8o"
  ["how-to-buy-backlinks-safely"]="M7lc1BCxL00"
  ["backlinks-for-local-seo"]="6McePZz4XZM"
  ["backlinks-for-new-websites"]="sOzlmuHvZUI"
  ["backlinks-vs-content-marketing"]="M7lc1BCxL00"
  ["best-backlink-checker-tools"]="3MnqGJb3PGE"
  ["best-sites-to-buy-backlinks"]="j8hQrMtqNrk"
  ["backlink-velocity-best-practices"]="lVKvr5PEf-g"
  ["backlink-quality-vs-quantity"]="3MnqGJb3PGE"
  ["paid-vs-free-backlinks"]="5HKvkBIBf8o"
  ["moz-link-explorer-guide"]="3MnqGJb3PGE"
  ["semrush-backlink-analysis"]="3MnqGJb3PGE"
  ["senuke-tng-for-links"]="jGxFxv2D5d0"
  ["seo-backlink-audit-tools"]="jGxFxv2D5d0"
  ["scale-link-building-agency"]="jGxFxv2D5d0"
  ["saas-link-building-tactics"]="j8hQrMtqNrk"
  ["safe-backlink-buying-guide"]="jGxFxv2D5d0"
  ["seasonal-link-building-campaigns"]="jGxFxv2D5d0"
  ["skyscraper-technique-for-links"]="pq6_sTu_TJ0"
  ["competitor-backlink-gap-analysis"]="3MnqGJb3PGE"
  ["backlink-indexing-techniques"]="lVKvr5PEf-g"
  ["best-backlink-checker-tools"]="3MnqGJb3PGE"
  ["cheap-backlinks-for-seo"]="jGxFxv2D5d0"
  ["buy-pbn-backlinks-safely"]="2R-3X3kY9W8"
  ["buy-backlinks-from-authority-sites"]="5HKvkBIBf8o"
  ["high-da-backlinks-for-sale"]="Q7F01_OXNqo"
  ["backlinks-for-new-websites"]="sOzlmuHvZUI"
  ["topical-authority-through-links"]="Q7F01_OXNqo"
  ["guest-post-link-building"]="BXp6pVW6zVc"
  ["resource-page-link-building"]="BXp6pVW6zVc"
  ["buzzsumo-for-link-opportunities"]="3MnqGJb3PGE"
  ["natural-link-building-patterns"]="sOzlmuHvZUI"
  ["tech-startup-backlinks"]="j8hQrMtqNrk"
  ["health-blog-link-building"]="jGxFxv2D5d0"
  ["podcast-guesting-for-links"]="BXp6pVW6zVc"
  ["majestic-seo-backlinks"]="3MnqGJb3PGE"
  ["buy-niche-relevant-backlinks"]="j8hQrMtqNrk"
  ["fiverr-vs-upwork-for-links"]="BXp6pVW6zVc"
  ["moz-link-explorer-guide"]="3MnqGJb3PGE"
  ["scale-link-building-agency"]="jGxFxv2D5d0"
  ["saas-link-building-tactics"]="j8hQrMtqNrk"
  ["measuring-roi-on-backlinks"]="jGxFxv2D5d0"
  ["senuke-tng-for-links"]="jGxFxv2D5d0"
  ["authoritative-backlinks-for-e-commerce"]="j8hQrMtqNrk"
  ["broken-link-building-method"]="pq6_sTu_TJ0"
  ["forum-link-building-tips"]="nZl1PGr6K9o"
  ["purchase-dofollow-backlinks"]="jGxFxv2D5d0"
  ["backlinks-vs-content-marketing"]="M7lc1BCxL00"
  ["high-quality-backlinks-from-.edu-sites"]="M7lc1BCxL00"
  ["backlink-building-for-beginners"]="Q7F01_OXNqo"
  ["competitor-backlink-gap-analysis"]="3MnqGJb3PGE"
  ["do-backlinks-still-work-in-2025"]="M7lc1BCxL00"
  ["paid-vs-free-backlinks"]="5HKvkBIBf8o"
  ["semrush-backlink-analysis"]="3MnqGJb3PGE"
  ["backlink-equity-calculation"]="WjQLLj0nBLY"
  ["manual-backlink-outreach"]="BXp6pVW6zVc"
  ["social-media-signal-backlinks"]="sOzlmuHvZUI"
  ["referral-traffic-from-backlinks"]="lVKvr5PEf-g"
  ["backlink-growth-tracking"]="3MnqGJb3PGE"
  ["best-backlink-checker-tools"]="3MnqGJb3PGE"
  ["best-sites-to-buy-backlinks"]="j8hQrMtqNrk"
  ["where-to-find-high-quality-backlinks"]="3MnqGJb3PGE"
  ["safe-backlink-buying-guide"]="jGxFxv2D5d0"
  ["high-quality-backlinks-vs-low-quality"]="3MnqGJb3PGE"
  ["buy-contextual-backlinks"]="3PU3HBk7YYU"
  ["backlink-disavow-tool-usage"]="VxW4KKvQlHs"
  ["influencer-outreach-for-backlinks"]="BXp6pVW6zVc"
)

echo "📹 Starting YouTube Video Replacement for All Pages"
echo "=================================================="

PAGES_DIR="src/pages"
UPDATED_COUNT=0
TOTAL_COUNT=0

# Process each .tsx file
for file in "$PAGES_DIR"/*.tsx; do
  FILENAME=$(basename "$file" .tsx)
  VIDEO_ID="${VIDEO_MAP[$FILENAME]}"
  
  if [ -z "$VIDEO_ID" ]; then
    VIDEO_ID="M7lc1BCxL00"  # Default fallback
  fi
  
  TOTAL_COUNT=$((TOTAL_COUNT + 1))
  
  # Use sed to replace video IDs - capture the video ID after embed/
  if sed -i.bak "s|youtube.com/embed/[^\"]*|youtube.com/embed/$VIDEO_ID|g" "$file"; then
    UPDATED_COUNT=$((UPDATED_COUNT + 1))
    echo "✓ $FILENAME"
  fi
done

echo "=================================================="
echo "Summary:"
echo "Total files processed: $TOTAL_COUNT"
echo "Files updated: $UPDATED_COUNT"
echo "✨ Video replacement complete!"
